### ISSUE TITLE
add pgAdmin users via a CLI or script call (RM #4125)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2483]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4125***
*Originally created by **Heiko Onnebrink** at 2019-03-29 11:43:36 UTC.*

today any user that wants to work with pgAdmin in server mode needs to be added by the admin manually within the UI.
For integration with self service portal the ability to add a user in an automated way via a script or cli call would eliminate this manual step.

add_user.py --id <me@somehwere> --pwd <supersecret>

or more generic

manage_user.py add --id <me@somehwere> --pwd <supersecret>
manage_user.py resetpwd --id <me@somehwere> --pwd <supersecret>
manage_user.py status --id <me@somehwere>
manage_user.py delete --id <me@somehwere>

**Comment by akshay-joshi** [comment]
Please consider [Enhancement](https://github.com/pgadmin-org/pgadmin4/issues/6638#issuecomment-1664796714) while implementing it.

**Comment by adityatoshniwal** [comment]
<img width="474" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/01f402a4-6417-411d-9138-1ea82f9db59c">
AFAIR, we discussed and Dave suggested that the key will be shown somewhere below the preference label. Was it missed? If we're going with showing using help button then it should be formatted.

**Comment by adityatoshniwal** [comment]
I found the following issues while testing:
1. `--no-console` doesn’t work. It is putting the result on screen. Same for all other commands.
<img width="1741" alt="Pasted Graphic" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/d04da6e5-bf25-493b-9a9c-875ffa65530a">

2. get-users in json format should be an array of objects, otherwise the JSON output cannot be used directly.
<img width="1131" alt="Pasted Graphic 1" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/9147fddc-f911-4240-aada-af78ef8002bc">

3. `--no-console` command is not needed for  get-users, get-prefs.

4. `get-prefs` does not show the value of the preference. It only shows the key. It would be also helpful to show the data type.
<img width="829" alt="Pasted Graphic 2" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/d8418ce1-7f95-470a-8eb9-69e5e33be95d">

5. JSON output for `get-prefs` should be key-value pairs.
<img width="1010" alt="Pasted Graphic 3" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/5033b949-0319-46bd-8b0f-2a021623d02e">

6. Not sure what is the --id here, can't find anything in docs either:
<img width="1349" alt="Pasted Graphic 4" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/61020d05-3e15-4426-b876-95a6c29ff306">

7. If I pass the prefs without value to set-prefs then it throws exception. I think the key should be validated first. Also, we discussed passing value separately as a third param to avoid confusion/complexity.
<img width="1373" alt="Pasted Graphic 7" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/f514b1af-2dfc-4367-93d4-df4273791f32">

8. `--no-console` is missing in set-prefs.

9. Login with an internal user for some email and run the below cmd. Then go to UI and open the users dialog. App crashes.
python setup.py update-user aditya.toshniwal14@gmail.com --nonadmin --inactive --json --no-console

10. Passing incorrect sqlite-path show full exception stack:
<img width="1257" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/e58e19c0-e99d-4c03-b5c6-b29e907bfa3e">


Suggestions:
1. Can we club add-user and add-external-user? Just like for all other commands —auth-source is the differentiator.
Also, —admin is missing in add-user.

<img width="1262" alt="Pasted Graphic 8" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/d6f78661-3a51-405a-af93-3176058a655d">

2. Should we rename `console/no-console` to simply `--silent`?

**Comment by khushboovashi** [comment]
Created pull request: https://github.com/pgadmin-org/pgadmin4/pull/7096

**Comment by adityatoshniwal** [comment]
Tested on https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-01-05/. Everything works fine except couple of minor issues:
1. If I run the command `python setup.py set-prefs aditya.toshniwal14@gmail.com "browser:processes:process_retain_days=true"` then it is success. Here, process retain days is a number.
2. Login with an internal user for some email and run the below cmd. Then go to UI and open the preferences dialog. App crashes. I think we should logout the user if it is inactive.
python setup.py update-user [aditya.toshniwal14@gmail.com](mailto:aditya.toshniwal14@gmail.com) --nonadmin --inactive --json --no-console

**Comment by adityatoshniwal** [comment]
The above mentioned issues are reported separately in #7116.
Works fine.
