### ISSUE TITLE
Autocommit for multi call procedure (RM #6758)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4559]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6758***
*Originally created by **Trang Le** at 2021-09-20 05:44:40 UTC.*

Hi guys,

I am trying to call 2 stored procedures in a run command that has commit statement. 

However, I received an error 'Invalid transaction termination'. I also add issue as attached files.

Could you help me on this issue?

Thanks,
Trang

**Comment by khushboovashi** [comment]
This implementation is by design from psycopg.
According to the documentation of psycopg, If a statement must be executed outside a transaction, it cannot be executed in batch with other statements, even if the connection is in autocommit mode. please 

References:
https://github.com/psycopg/psycopg/discussions/797
https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#multiple-statements-in-the-same-query (Warning block)

So, closing the issue.
