### ISSUE TITLE
'rawunicodeescape' codec can't decode bytes in position 142-145: truncated \uXXXX escape (RM #7165)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#4891]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7165***
*Originally created by **Danielle Lamarre** at 2022-02-08 19:30:21 UTC.*

I have a table with a field that contains "\" or "/" characters etc. With PGADMIN 3 I could see the contents of this field but with PGADMIN 4 impossible to see the contents of the file. RUSH, URGENT need to fix this problem

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by FaharAbbasRizvi** [comment]
This is not fully fixed in psycopg3:

How I tested:
1. create following table:
CREATE TABLE IF NOT EXISTS public."!@#$%^&*()_+{}|:<>?=|}{:<>?/.,;\"
(
    "!@#$%^&*()_+{}|:<>?=|}{:<>?/.,;\" numeric(100,0) NOT NULL,
    CONSTRAINT "!@#$%^&*()_+{}|:<>?=|}{:<>?/.,;\_pkey" PRIMARY KEY ("!@#$%^&*()_+{}|:<>?=|}{:<>?/.,;\")
)

TABLESPACE pg_default;
2. Table created
3. Go into the view data
4. Add Rows 100. 200, 300
5. Click on Save button
6. Following error message is displayed

Successfully run. Total query runtime: 422 msec.
0 rows affected.Single '}' encountered in format string
<img width="1084" alt="Screen Shot 2023-02-23 at 12 59 13 PM" src="https://user-images.githubusercontent.com/43006122/220852039-23a30824-fbd5-40f7-a067-2ec1474878b4.png">

**Comment by khushboovashi** [comment]
I can not reproduce this issue with SQLASCII database.


![Image](https://user-images.githubusercontent.com/14345545/222088997-b4d65362-908a-412e-aa2a-0848290b4eda.png)

**Comment by khushboovashi** [comment]
I was able to reproduce this issue. PR Raised.

**Comment by FaharAbbasRizvi** [comment]
This is fixed in the last snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-03-13/
