### ISSUE TITLE
ERD line anchor points (RM #7544)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5199]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7544***
*Originally created by **Paul Farry** at 2022-07-10 00:47:11 UTC.*

If would be nice if you could add additional points to a line that is connecting 2 entities so that you can control how that line connects/paths between entities

**Comment by dcr8898** [comment]
I would like to offer an observation that might point the way to an incremental path to resolve this issue (and perhaps offer progress for pgadmin-org/pgadmin4#6592 as well).

I notice that if I perform the following steps:

- manually re-arrange the entity layout in the diagram,
- delete a line (in the ERD tool they are called "links", which is correct?), and 
-  re-add the same link-line with the "1M" or "MM" buttons

Then I get nice, straight link-lines with right-angles. These link-lines are also easier to edit, because I can move the vertical and horizontal segment easily without dealing with angled segments (that I don't really want anyway).

This suggests that the algorithm to draw link-lines for manually added relations may be different than the algorithm used when initially drawing the diagram. For example, I'm pretty new to pgAdmin, but I haven't seen any angled link-lines when added manually, but they are common on any reasonably complex auto-generated ERD.

Would it be possible to invoke a redraw of a link-line as if it were manually added? If so, then triggering such redraws would make re-arranging the diagram easier and more pleasant. The redraw could be triggered any number of ways:

- Automatically whenever a table is moved.
- Manually for the whole diagram, perhaps with another button in the menubar.
- Manually for an individual link-line, maybe with a right-click context menu on the link-line or with a button on the menubar.

An incremental path forward could look something like:

- Manually triggered re-draw of link-lines.
- Auto-redraw of link lines triggered by movement of an entity in the ERD.
- Manual editing of link-line nodes and segments.

I hope this is helpful. I do not know much Python or React, but I am happy to contribute however I can, including pairing with someone more knowledgeable.

Thank you!

**Comment by adityatoshniwal** [comment]
Thank you for your inputs @dcr8898. I would definitely give a try. It is related to https://github.com/pgadmin-org/pgadmin4/issues/6592, not this.

**Comment by adityatoshniwal** [comment]
I'm closing this issue in favour of right angled links only. This also makes switching anchor point on either side even more complex.
