### ISSUE TITLE
PG Admin 6.14 issue "variable not found in subplan taget list"

### ISSUE THREAD

**Issue by svinsightdata** [pgadmin-org/pgadmin4#5385]
Since upgrading to 6.14 I am getting errors when trying to open the properties window for some tables.
![image](https://user-images.githubusercontent.com/99749172/193024038-0c96f656-5878-4c02-ba04-49d37e8f08ec.png)

**Comment by akshay-joshi** [comment]
Hi @svinsightdata 
Which database version are you using?
Can you please provide the DDL of the table where the issue occurs?

**Comment by svinsightdata** [comment]
Hi @akshay-joshi 

This concerns version "PostgreSQL 12.10, compiled by Visual C++ build 1914, 64-bit"

Please see attached for the DDL of an table where we experience the issue:

[ddl.txt](https://github.com/pgadmin-org/pgadmin4/files/9687386/ddl.txt)

**Comment by dpage** [comment]
Note that the error message comes directly from PostgreSQL, and is actually an XX class error which should never happen (https://www.postgresql.org/docs/12/errcodes-appendix.html). At least one bug that could cause this was fixed in PostgreSQL 12.11 - see https://github.com/postgres/postgres/commit/32e801676b1ef821c6ee308f7ea42386a3e15768

I would suggest upgrading PostgreSQL.

**Comment by adityatoshniwal** [comment]
Hi @svinsightdata,

We're closing the issue. In case it does not fix with upgrade, you can re-open.
