### ISSUE TITLE
Query tool does not commit after every statement

### ISSUE THREAD

**Issue by fans2619** [pgadmin-org/pgadmin4#5497]
Is the query tool treating all statements as a single transaction? Currently if one insert fails, all other inserts are not being committed. It's good if there's option to auto commit after executing every statement.

**Comment by yogeshmahajan-1903** [comment]
@fans2619 You can set auto commit option from query tool. PFA SS. 
<img width="1390" alt="Screenshot 2022-11-04 at 17 36 46" src="https://user-images.githubusercontent.com/16016019/199968997-46c1916e-3fe3-4ca2-9ca3-c65b3a2d09f0.png">

**Comment by fans2619** [comment]
For example in this case because stmt#4 fails, nothing is committed after execution. It would be nice if there's an option such that the table is still created and 123 is inserted, because each statement should by default be in one separate transaction.

![image](https://user-images.githubusercontent.com/68739475/199970145-dbdff523-1a34-4deb-942d-05717e7ab9b4.png)

**Comment by dpage** [comment]
pgAdmin will execute the entire script (or selected part of it) as one statement. In order to execute each command individually we'd need to parse the script ourselves and then execute each part. That's likely to be error prone, and would be very different behaviour from the way pgAdmin has worked over the last 20 years or so. I doubt that's a change we're likely to make any time soon.

**Comment by fans2619** [comment]
Noted. Thanks a lot for the info!
