### ISSUE TITLE
Group Functions to simplify browsing

### ISSUE THREAD

**Issue by wpeaton** [pgadmin-org/pgadmin4#5545]
If you have lots of installed functions in your database, browsing for functions you wrote yourself can be tedious. For example, in image below there are a ton of _int_ functions you have to scroll through before you can get to the good stuff. 

It would be nice if PgAdmin automatically could somehow automatically group functions (roll them up into a tree node) so users could avoid scrolling through all of them.

![image](https://user-images.githubusercontent.com/17578088/202290498-1ee5de74-27e5-42db-a718-f16f39208846.png)

**Comment by akshay-joshi** [comment]
@wpeaton 

It's been a while since pgAdmin displayed tree items as collection nodes and their children. This requires a change in the basic structure and many other modules as well. 

As we won't be doing this anytime soon, we're closing it. 

To resolve this, you can do the following:
1) Set Preferences -> Browser -> Display -> Show System Objects to False. (If you are not working on system objects)
2) Use the [Search Object](https://www.pgadmin.org/docs/pgadmin4/latest/search_objects.html) feature.
