### ISSUE TITLE
Rewrite menus to remove Bootstrap/jQuery

### ISSUE THREAD

**Issue by akshay-joshi** [pgadmin-org/pgadmin4#5615]

**Comment by nikhil-mohite** [comment]
Issues found in testing:
1. Quick search is showing spinner and getting console error for searching menu items, help article search is working fine.
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/69510038/211296414-3ab241fe-239d-4d8e-8711-d8b06bd54c64.png">
2. Menu dropdown is showing behind the query tool loading screen(This issue is reproducible only if the open query tool is taking  time)
<img width="1520" alt="Screenshot 2023-01-09 at 4 41 16 PM" src="https://user-images.githubusercontent.com/69510038/211296863-17a3ed9a-1bf9-49f8-bf58-4fc210a6026b.png">

**Comment by nikhil-mohite** [comment]
Issues found in testing:
1. Right-click on any node to open the context menu, (considering the tree has a vertical scrollbar), and now scroll the tree, context menu position is fixed, the expected behavior if the context menu is open user should not able to scroll the tree.


https://user-images.githubusercontent.com/69510038/211313446-c4b40a13-d496-4676-9090-a68fe230d483.mov

2. Selection of sub-menus should close the menu, select the `Lock Layout -> Prevent Docking` sub-menu is not getting closed.
3. If try to open the context menu on the same node multiple times, it shows the browser's default context menus.(This is only reproducible on the browser Firefox and OS Centos 7, on macOS not able to reproduce the issue)

https://user-images.githubusercontent.com/69510038/211314626-c2719e24-41c7-485b-a4e7-535513a11439.mov

**Comment by nikhil-mohite** [comment]
> Issues found in testing:
> 
> 1. Quick search is showing spinner and getting console error for searching menu items, help article search is working fine.
> 
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/69510038/211296414-3ab241fe-239d-4d8e-8711-d8b06bd54c64.png">
> 
> 2. Menu dropdown is showing behind the query tool loading screen(This issue is reproducible only if the open query tool is taking time)
> <img alt="Screenshot 2023-01-09 at 4 41 16 PM" width="1520" src="https://user-images.githubusercontent.com/69510038/211296863-17a3ed9a-1bf9-49f8-bf58-4fc210a6026b.png">
> 
> 3. Disable menus showing in the context menu. (In older versions disable menus are hidden in the context menu)
> <img alt="Screenshot 2023-01-09 at 5 18 19 PM" width="534" src="https://user-images.githubusercontent.com/69510038/211301784-aa1bacb4-fd38-42c5-879e-8d35b5bfd86a.png">

Resolved, Verified on latest candidate build https://developer.pgadmin.org/builds/2023-01-09-2/
OS: CentOS7
Browser: FireFox.

**Comment by nikhil-mohite** [comment]
> Issues found in testing:
> 
> 1. Right-click on any node to open the context menu, (considering the tree has a vertical scrollbar), and now scroll the tree, context menu position is fixed, the expected behavior if the context menu is open user should not able to scroll the tree.
> 
>  tree-context-scroll-issue.mov 
> 2. Selection of sub-menus should close the menu, select the `Lock Layout -> Prevent Docking` sub-menu is not getting closed.
> 3. If try to open the context menu on the same node multiple times, it shows the browser's default context menus.(This is only reproducible on the browser Firefox and OS Centos 7, on macOS not able to reproduce the issue)
> 
>  browser-conext-menus.mov

Resolved, Verified on latest candidate build https://developer.pgadmin.org/builds/2023-01-13-1/
OS: CentOS7 (Browser: Firefox.), macOS 12.6(Monterey) [Desktop application]
