### ISSUE TITLE
Please build apt packages for Debian testing and sid

### ISSUE THREAD

**Issue by mbehrle** [pgadmin-org/pgadmin4#5681]
According to https://www.pgadmin.org/download/pgadmin-4-apt/ only Debian releases up to Debian 11 (bullseye) are built. Please build also for Debian testing (currently bookworm) and sid.

Thanks!

**Comment by stefanhh0** [comment]
Since debian testing/unstable just dropped python-3.9 support this depends on:
https://github.com/pgadmin-org/pgadmin4/issues/4466
See as well my comment: https://github.com/pgadmin-org/pgadmin4/issues/4466#issuecomment-1379665742

**Comment by mbehrle** [comment]
> Since debian testing/unstable just dropped python-3.9 support this depends on: #4466 See as well my comment: [#4466 (comment)](https://github.com/pgadmin-org/pgadmin4/issues/4466#issuecomment-1379665742)

Well, this is AFAICS only a matter to build on the correct system. I am rebuilding pgadmin4 on every release in a Debian testing chroot and the resulting packages just work fine.

**Comment by mbehrle** [comment]
> We have limited resources to support builds for additional platform variations, and it's not likely we'll be able to support testing versions ahead of other platforms that people are asking for such as Arch Linux or ARM64 variants.

Well, Debian testing is named testing, but is far from being a 'test' version. It may be rather considered the rolling release of Debian and is in term of stability comparable to regular releases of other distributions. I would ask to reconsider the build for Debian testing.

**Comment by stefanhh0** [comment]
Hello @mbehrle and @dpage,

> > Since debian testing/unstable just dropped python-3.9 support this depends on: #4466 See as well my comment: [#4466 (comment)](https://github.com/pgadmin-org/pgadmin4/issues/4466#issuecomment-1379665742)
> 
> Well, this is AFAICS only a matter to build on the correct system. I am rebuilding pgadmin4 on every release in a Debian testing chroot and the resulting packages just work fine.

I tried to build the pgadmin4 packages on testing myself, however I couldn't get it running. I ran into a  npm / js dependency problem that I wasn't able to resolve myself, thus gave up on it.

Because of that I decided for the workaround to have python3.9 packages from stable in my testing distro. This currently works but may break any day due to changes in testing. Going back to debian stable is not an option for me since my hardware is not supported on debian stable.

I just checked the ubuntu packages and found that the kinetic package was built with python >= 3.10. So it is possible to install kinetic package (https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/kinetic) on debian/testing. After switching the repository and re-installing the pgadmin4 packages, I was able to drop debian/stable python3.9 packages.

These are all workarounds for getting pgadmin4 running on debian/testing. I agree with @mbehrle that debian testing should be considered a rolling release.

https://wiki.debian.org/DebianTesting:
The code name for the next stable release, e.g. "bookworm", will track "bookworm" through its transition into "stable" and later oldstable, while "testing" will keep rolling on after a new stable release. If you would rather track the Bookworm release as it becomes stable, update your apt sources replacing "stable" or "testing" with "bookworm". 

And so it would be really great for debian users to also have a debian/testing package available.

**Comment by stefanhh0** [comment]
From what I can see in pgadmin4 is, that the support for rolling releases would be something new for pgadmin4, since all all linux packages  (rpm and dpkg) are built for specific OS Releases that are not rolling.

For a list of rolling linux distros have a look here:
https://itsfoss.com/best-rolling-release-distros/

In order to support rolling releases with rpm and dpkg properly, i guess it would be a good idea to always include the python [major].[minor] version as a dependency in the packages, as mentioned in:  https://github.com/pgadmin-org/pgadmin4/issues/5727.
