### ISSUE TITLE
Not able to changes user password in server mode

### ISSUE THREAD

**Issue by pravesh-sharma** [pgadmin-org/pgadmin4#6274]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

When trying to changes user password using change password getting SMTP socket error.

**To Reproduce**

1. Login to pgAdmin using your credentials.
2. Click on username at right top corner and then on `Change Password`
3. Try changing the password, getting error

**Expected behavior**

User should be able to change his/her password.

**Screenshots**
<img width="1595" alt="Screenshot 2023-05-11 at 11 01 57 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/78c55561-77b5-4ecd-98f8-e92f7f054b26">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - Version: 7.1
 - Mode: Server
 - Browser (if running in server mode): chrome
 - Package type: Python

**Comment by anilsahoo20** [comment]
In other environments of pgAdmin like pip/Debian/rpm packages, the user gets SMTP socket error on change password or forgot password or reset password of pgAdmin. It is mandatory to set the SMTP configuration on config_local.py by overriding the config.py file.

But pgAdmin in Docker, by default uses the Postfix mail transfer agent so we did not get the SMTP error and the action is a success, but it does not send any email on change password or forgot password or reset password, as it needs additional setup of Postfix to send email. We can use other external mail server also by setting the value of `PGADMIN_DISABLE_POSTFIX` to something else so that Postfix will be disabled. Please refer pgAdmin docs [here](https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#:~:text=PGADMIN_DISABLE_POSTFIX)

**Comment by nikhil-mohite** [comment]
Resolved, Verified on candidate build: https://developer.pgadmin.org/builds/2023-09-18-1/
OS: Windows 10
Package: Pip whl
Mode: Server Mode
