### ISSUE TITLE
Expose Clear Servers as a setup.py argument.

### ISSUE THREAD

**Issue by bobpach** [pgadmin-org/pgadmin4#6602]
**Describe the solution you'd like**
I would like the ability to be able to call clear servers to unregister all servers when they are no longer available.

I am writing a sidecar container for pgadmin that will wakeup on a configured interval and connect to the kubernetes cluster that pgadmin is running in.  It identifies all postgres clusters by label and builds a servers.json file.  It then invokes setup.py.  As postgres servers are removed it "unregisters" them by way of rebuilding the json file with the remaining servers and reapplying it.  However, when no postgres servers are remaining there is no good way to remove the last registration.  

**Describe alternatives you've considered**

I tried sending an empty server list:
{
    "Servers": {}
}

It doesn't error out.  However, the Server Group section of the UI and the ability to manually add servers breaks.  The web page just locks up on refresh or new page load after clicking on add new server.

**Additional context**
It is my hope to have the ability to add or remove servers from 0:n and back to 0 again as needed using an external process like a sidecar or kubernetes job.

**Comment by benjaminjb** [comment]
Following up on this: I'm a little unclear why `clear_database_servers` deletes the servers and the servergroups?

https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/utils/__init__.py#L770C5-L770C27

**Comment by adityatoshniwal** [comment]
> Following up on this: I'm a little unclear why `clear_database_servers` deletes the servers and the servergroups?
> 
Because that is intended.
> https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/utils/__init__.py#L770C5-L770C27
> 
> ETA: follow-up to the follow-up: am I reading this right that this func deletes all servers for a user twice and if so, why?
You're right, the 2nd one is irrelevant. It can be removed, although it has no side effect.

**Comment by benjaminjb** [comment]
OK, so: 

Requirement 1: when we `clear_database_servers`, we want to clear servers and servergroups. (Because we don't want to leave servergroups around without servers -- because ... hmmm, well, multiple servergroups without servers is bad UX?)

Requirement 2: every user has to have at least one servergroup (which is why user creation includes a default servergroup [here](https://github.com/pgadmin-org/pgadmin4/blob/37dced23f0d921e858128554b5d5136e7faecc98/web/pgadmin/tools/user_management/__init__.py#L503)).

So one possible solution would be to check during the [load](https://github.com/pgadmin-org/pgadmin4/blob/37dced23f0d921e858128554b5d5136e7faecc98/web/pgadmin/tools/user_management/__init__.py#L503) process: if this user has no servergroups (because they've been dropped due to Requirement 1) AND if the `servers` length is 0, then add a default servergroup just like we do during user creation.

How does that solution sound?
