### ISSUE TITLE
On Mac pressing CMD + W should only close current tab, not entire app

### ISSUE THREAD

**Issue by OskarEichler** [pgadmin-org/pgadmin4#6814]
On Mac it would be great that CMD + W only closes the current tab, for example the current Query Tool tab and not the entire PGAdmin application. For that purpose CMD + Q is usually used. This would then align with the same behavior pretty much all browsers have (like Chrome, Firefox, etc). Did this a bunch of times where I press CMD + W to close the current tab, but then the entire app closes and I lose my other tabs.

**Comment by akshay-joshi** [comment]
@OskarEichler 

Partial resolution for this issue has been implemented in pgAdmin 4 v8.1, where pressing 'CMD + W' will no longer close the entire application. The outstanding fix involves capturing the 'CMD + W' keypress event to specifically close the active tab. Therefore, this issue is being kept open for further refinement.

**Comment by adityatoshniwal** [comment]
The remaining part will be taken care in #6572.
