### ISSUE TITLE
Commit occurs on query run while auto commit is disabled.

### ISSUE THREAD

**Issue by Nikem77** [pgadmin-org/pgadmin4#6975]
**_Please note that security bugs or issues should be reported to security@pgadmin.org._**

**Describe the bug**

Issue is floating. Mostly it occurs after pgadmin lost connection to the DB and the query was executed after reconnection. Caught this issue on UPDATE query luckily on test server.

1. Go to Execution option
2. Uncheck "Auto commit" 
![image](https://github.com/pgadmin-org/pgadmin4/assets/11626066/645df69b-ea74-4295-8c2a-8c554751d907)
3. Execute any DML query
4. Your query got commited to the server; buttons commit and rollback stays inactive (grey); explicit execution of ROLLBACK returns message 
```
WARNING:  there is no transaction in progress
ROLLBACK
```

Expected: query executed but could be commited or rolled back
Workaround: Click "new query tool with the same connection" (Alt+Shift+Q) and run query there.

Version 7.6
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.77.0
Browser Chromium 114.0.5735.91
Operating System Windows-10-10.0.19044-SP0

![image](https://github.com/pgadmin-org/pgadmin4/assets/11626066/42907938-84ed-44e1-a131-3eb4080a9200)

![image](https://github.com/pgadmin-org/pgadmin4/assets/11626066/358a4524-4306-4a41-a0b8-7ed5873f9807)

**Comment by akshay-joshi** [comment]
@Nikem77 

I have tried the steps that you have mentioned, but after a couple of attempts, the issue is not reproducible.
Steps to Reproduce:
1) Open a query tool, and run Insert statement.
2) Uncheck "Auto commit".
3) Stop the database service.
4) Execute the Insert statement, which throws an error, and the below popup dialog comes
<img width="955" alt="Screenshot 2023-11-17 at 2 55 07 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/26f7f254-2f0d-451d-a578-16b56ac97198">

5) Start the Database service and Click on the Continue button. Query gets executed and both commit and rollback button is enabled as shown below:
<img width="708" alt="Screenshot 2023-11-17 at 2 55 21 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/949bc379-5e89-48be-8f58-1594e7faccf7">

6) By clicking on the Commit button, the record is inserted into the table.
<img width="689" alt="Screenshot 2023-11-17 at 2 55 48 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/3306e04e-047c-4133-9ffe-2d005bbad705">

**Comment by Nikem77** [comment]
@akshay-joshi, I described my lasts steps when I caught that issue last time. That's correct, the issue doesn't occur every time, I don't know what to do exactly to reproduce it. May it be server specific?

**Comment by yogeshmahajan-1903** [comment]
@Nikem77 
Closing the issue as of now. Feel free to open if you are able to reproduce and have exact reproduction steps.
