### ISSUE TITLE
no python typer module in official docker image

### ISSUE THREAD

**Issue by jkreet** [pgadmin-org/pgadmin4#7281]
**Describe the bug**

no python **typer** module in official docker image dpage/pgadmin4:8.4

**To Reproduce**

1. docker pull dpage/pgadmin4:8.4
2. start container
3. run from container:
    _python setup.py load-servers servers.json from container_
4. got an error ModuleNotFoundError: No module named 'typer'

**Expected behavior**

run script without errors

**Error message**

Traceback (most recent call last):
  File "/pgadmin4/setup.py", line 15, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'

**Comment by stephdl** [comment]
this bug is still true with 8.6 docker container

**Comment by stephdl** [comment]
/pgadmin4 $ python setup.py load-servers servers.json --replace
Traceback (most recent call last):
  File "/pgadmin4/setup.py", line 15, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'

**Comment by stephdl** [comment]
answering myself 

`podman exec -u pgadmin -ti pgadmin-app /venv/bin/python3 setup.py load-servers servers.json --replace`

**Comment by Basil-Dot-Work** [comment]
For those who may have missed the solution in that last post by stephdl:

-  The problem is that the Docker image comes with multiple installations of Python.  The default executable is `/usr/bin/python`. 
-  To access the necessary modules missing per the error message, you must use a different Python executable. Use `/venv/bin/python3` explicitly. 

Within the container:

```bash
/venv/bin/python3 /pgadmin4/setup.py add-user "student@example.com" "letmein" --role "User";
```

From Podman (or Docker):

```bash
podman container exec pgadmin-container /venv/bin/python3 /pgadmin4/setup.py add-user "student@example.com" "letmein" --role "User";
```
