### ISSUE TITLE
cannot modify column datatype in table definition

### ISSUE THREAD

**Issue by shambakey1** [pgadmin-org/pgadmin4#7533]
Hi

I'm trying to change the data type of a column (which is "text") after the table has been saved. Pgadmin 4 does not show all different data types. Pgadmin 4 only shows the data types that relate to the original column data type (e.g., "name", "text[]",.. etc). I had to delete the column and create it again with the new data type.

I don't know how to solve it without column recreation.

Regards

**Comment by akshay-joshi** [comment]
@shambakey1 

This is by design. If you can read the docs for the ALTER TABLE ... ALTER COLUMN then one of the ways to do it is by "[ USING expression ]" clause. I have tried when data for that column is easily convertible like an integer(or similar) to character varying, and it works. But what if when we try to convert from text/character to integer or similar type. It gives below error:
"invalid input syntax for type bigint:"

**Comment by shambakey1** [comment]
Many thanks
