### ISSUE TITLE
Relationship lines in ERD are weird as hell

### ISSUE THREAD

**Issue by RieBi** [pgadmin-org/pgadmin4#7730]
**Describe the bug**

Relationship lines are really complicated and not intuitive to understand what's going on when you look at the diagram. More than that, in some scenarios where the lines could be very simple, it extends to bottom resulting in monstrous looks.

**To Reproduce**

1. Go to any relatively complex database with multiple connections
2. Right click on the respective schema containing all the tables
3. Select "ERD For Schema"
4. See the not the best thing created, but even horrible things to emerge when you try to move elements around.

**Expected behavior**

A clear and concise view of relationships between tables, and it responds well when you move them manually.

**Screenshots**

Not screenshot, but see a video below.

**Desktop (please complete the following information):**
 - OS: Windows-10-10.0.19045-SP0
 - Version: 8.7
 - Mode: Desktop?

https://github.com/user-attachments/assets/a86acda1-0fde-4e79-b361-d9ba0442d4ea

**Comment by adityatoshniwal** [comment]
This duplicates #6592.

**Comment by aaronpeacock** [comment]
So, why not let people DRAW the line themselves?  
If I click and select the line, it's annoying to try to drag it around
and then get these strange lines that go everywhere but NOT direct...

![pgadmin_line_weirdness](https://github.com/user-attachments/assets/b2cf09fb-303e-4ba8-a3c6-5037cf158227)

If I could simple DRAW the line connecting them WHERE I WANT IT, we don't need any fancy computer guesswork or algorithmic wrongness that I don't want anyway, IMO...

I mean:
1) click line to select
2) can drag around, but at some point it gets ruined and messy
3) click back on one of the points (either side) and it goes highlighted a color and bright-colored DRAWING line appears and we click on the other point in a straight line and the line goes straight again.

Either that or we need some tools.
"Auto-align" button destroys everything. It's what produced the problems in the first place. It doesn't affect "selected items" only but affects everything always.
Tool:
- to make line straight (shortest path, no angles, no strange peaks, no excursions/detours for no reason)


But honestly, I think just being able to manually override the bad computer guesses is worth a LOT.
Otherwise, it's frustrating to spend days designing a schema and then not be able to work with the ERD tool after a certain point simply due to funky lines.

**Comment by KyrMitsos** [comment]
Is anyone working on this?
