### ISSUE TITLE
pgAdmin fails to return results rows from FUNCTION

### ISSUE THREAD

**Issue by duncangroenewald** [pgadmin-org/pgadmin4#8010]
pgAdmin fails to display the data rows from a FUNCTION.

See the example function below

```
CREATE OR REPLACE FUNCTION tablerows(ref1 refcursor)
RETURNS refcursor AS $$
BEGIN
OPEN ref1 FOR
WITH tbl AS
  (SELECT table_schema,
          TABLE_NAME
   FROM information_schema.tables
   WHERE TABLE_NAME not like 'pg_%'
     AND table_schema in ('makespace'))
SELECT table_schema,
       TABLE_NAME,
       (xpath('/row/c/text()', query_to_xml(format('select count(*) as c from %I.%I', table_schema, TABLE_NAME), FALSE, TRUE, '')))[1]::text::int AS rows_n
FROM tbl
ORDER BY rows_n DESC;
RETURN ref1;
END; $$ LANGUAGE plpgsql;

And this SQL is used to fetch the results from the function 

BEGIN;
SELECT tablerows('tables');
FETCH ALL FROM "tables";
COMMIT;
```

See attached image for the pgAdmin screen showing the results columns but no data rows.

Version 8.12
Application Mode Desktop
Commit: a0aa1855186bbe769182e797dc546812ed4dc720 2024-09-20
Current User pgadmin4@pgadmin.org
Electron Version 32.1.1
Browser Chrome 128.0.6613.137
Operating System macOS-14.6.1-arm64-arm-64bit

<img width="416" alt="Screenshot 2024-10-05 at 8 12 21 AM" src="https://github.com/user-attachments/assets/13d4b0e6-6442-467e-aaf2-a57f70f45da2">

**Comment by pravesh-sharma** [comment]
The actual issue was that when multiple queries were executed together in the query tool, it returned results and messages from the last executed query, which were not being handled correctly. We have fixed this, and now it only shows the result and message from the last executed query.

The issue is fixed and tested on the latest snapshot [build](**url**).
